apiVersion: tunnel.nubulusnetwork.es/v1alpha1
kind: TunnelRoute
metadata:
  labels:
    app.kubernetes.io/name: nubuluscloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: tunnelroute-sample
spec:
  # TODO(user): Add fields here
